owner: dorwardtech
repo: status

sites:
  - name: Laser Sports Archive
    url: https://archive.lasersports.au

status-website:
  cname: status.tr1cky.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DorwardTech Uptime
  introTitle: "**Upptime** Tr1cky's active projects / Services"
  introMessage: Things & Stuff
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
