owner: dorwardtech
repo: lsa-status

sites:
  - name: Laser Sports Archive
    url: https://archive.lasersports.au
    maxResponseTime: 5000
    
  - name: Laser Sports Archive - API
    url: https://archive.lasersports.au/api/v2/authorize?key1=$LSA_KEY_1&key2=$LSA_KEY_2
    
  - name: Laser Sports Archive - Cloudflare R2 Storage (ZLTAC)
    url: $R2_ENDPOINT/zltac
    maxResponseTime: 5000
    
  - name: Laser Sports Archive - Cloudflare R2 Storage (THEARCHIVE)
    url: $R2_ENDPOINT/thearchive
    maxResponseTime: 5000
    

status-website:
  theme: dark
  cname: status.lasersports.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Live Status - Laser Sports Archive
  introTitle: "**Laser Sports Archive Status**"
  introMessage: Laser Sports Archival Project
  navbar:
    - title: Status
      href: /
    - title: Laser Sports Archive
      href: https://archive.lasersports.au
