owner: dorwardtech
repo: status

sites:
  - name: Laser Sports Archive
    url: https://archive.lasersports.au
    maxResponseTime: 5000
  - name: Laser Sports Archive API
    url: https://archive.lasersports.au/api/v2/authorize?key1=$LSA_KEY_1&key2=$LSA_KEY_2
  - name: Laser Sports League Manager
    url: https://lslm.lasersports.au
    maxResponseTime: 5000
  - name: Laser Sports Competition Manager
    url: https://lscm.lasersports.au
    maxResponseTime: 5000
 

status-website:
  theme: dark
  cname: status.tr1cky.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Live Status - Tr1cky
  introTitle: "**Tr1cky's Active Projects / Services**"
  introMessage: Things & Stuff
  navbar:
    - title: Status
      href: /
    - title: Personal Site
      href: https://tr1cky.au
